name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

env:
  NODE_VERSION: 22.18.0

jobs:
  setup:
    name: 🧩 Setup and Validate
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Restore dependencies cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: deps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: deps-

      - name: Install dependencies
        run: pnpm install

      - name: Run Type Check
        run: pnpm run type-check

      - name: Run Lint and Format
        run: pnpm run lint:fix

  tests:
    name: 🧪 Unit + E2E Tests
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, e2e]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: deps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: deps-

      - name: Install dependencies
        run: pnpm install

      - name: Setup Playwright
        if: matrix.test-type == 'e2e'
        uses: microsoft/playwright-github-action@v1

      - name: Run Tests
        run: |
          if [ "${{ matrix.test-type }}" = "unit" ]; then
            pnpm run test:run
          else
            pnpm run test:e2e
          fi

  build:
    name: 🏗️ Build App
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: deps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: deps-

      - name: Install dependencies
        run: pnpm install

      - name: Build Production
        run: pnpm run build:production

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next/

  deploy:
    name: 🚀 Deploy to Vercel
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
